spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plans_api_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: Plans-Api  
    
#  boot:
#    admin:
#      client:
#        url: http://localhost:8081/    
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - '*'   
#
#server:
#  port: 2222
           
    